name 'swisnap'
maintainer 'Dawid Smiech'
maintainer_email 'dawid.smiech@solarwinds.com'
license 'All Rights Reserved'
description 'Installs/Configures swisnap'
version '0.1.0'
chef_version '>= 12.14'
depends 'packagecloud'
