name 'swisnap'
maintainer 'SolarWinds Worldwide, LLC'
maintainer_email 'support@appoptics.com'
license 'Apache-2.0'
description 'Install SolarWinds Snap Agent for Linux and Windows'
version '0.2.0'
chef_version '>= 16.2'
depends 'packagecloud'
