---
version: 2.1
commands:
  run_tests:
    description: "Run Kitchen tests"
    steps:
      - checkout

      - run:
          name: "Install Chef"
          command: curl -L https://www.chef.io/chef/install.sh | sudo bash

      - run:
          name: ubuntu-1804
          command: kitchen test ubuntu-1804

jobs:
  test-kitchen:
    machine:
      image: ubuntu-2004:202010-01
    environment:
      KITCHEN_LOCAL_YAML: kitchen.dokken.yml
      CHEF_LICENSE: "accept-no-persist"
    steps:
      - run_tests

workflows:
  version: 2.1
  build_and_test:
    jobs:
      - test-kitchen 
