---
version: 2.1

jobs:
  test-kitchen:
    machine:
      image: ubuntu-2004:202010-01
    environment:
      KITCHEN_LOCAL_YAML: kitchen.dokken.yml
      CHEF_LICENSE: "accept-no-persist"
    steps:
      - checkout

      - run:
          name: "Install Chef"
          command: sudo bash -c "$(curl -sSL https://www.chef.io/chef/install.sh)" -s -P chefdk

      - run:
          name: ubuntu-1804
          command: kitchen test ubuntu-1804

workflows:
  version: 2.1
  build_and_test:
    jobs:
      - test-kitchen 
