---
version: 2.1
commands:
  run_tests:
    description: "Run Kitchen tests"
    steps:
      - checkout
      - run
        name: "Install Chef"
        command: 

      - run:
        name: "Run tests"
        command: kitchen test XXXX

jobs:
  debian8:
    environment:
      KITCHEN_LOCAL_YAML: kitchen.dokken.yml
      CHEF_LICENSE: "accept-no-persist"
    steps:
      - run_tests

workflows:
  version: 2.1
  build_and_test:
    jobs:
      - debian-8
