default['swisnap']['swisnap_package_name'] = 'solarwinds-snap-agent'
default['swisnap']['swisnapd_service'] = 'swisnapd'
default['swisnap']['windows_installator_path'] = ''
default['swisnap']['swisnap_linux_user'] ='isolarwinds'
default['swisnap']['swisnap_linux_group'] = 'solarwinds'
